### get /
GET http://localhost:3000

### register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@gmail.com",
    "password": "pass1234",
    "confirmPassword": "pass1234"

}

### login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "aosakhogba@gmail.com",
    "password": "pass1234"
}

### get user profile /PROFILE (protected)
GET http://localhost:3000/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtazF1NGRyODAwMDBobmh1enR2M3c3MzUiLCJpYXQiOjE3Njc3OTA0MTksImV4cCI6MTc2Nzg3NjgxOX0.Mb_sDTY5GkhmmirgU-nZ-jGwHELQ3DExNIIcagjKXmQ

### get all articles
GET http://localhost:3000/posts

### create article /CREATE (protected)
POST http://localhost:3000/posts/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtazFzeTFvNTAwMDB3NGh1ZWpkcjJ2c3oiLCJpYXQiOjE3Njc2NTc5MzIsImV4cCI6MTc2Nzc0NDMzMn0.0S3P2dFKXdp0gkZXvRPUO3ishST1QD0kgFhfYadf5rE

{
    "title": "My second Article",
    "content": "lorem ipsum dolor sit amet",
    "published": true
}

### update article /UPDATE/:ID (protected)
PUT http://localhost:3000/posts/update/cmjroorzi0000tihue0pr2q6d
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtanF5NXVjNDAwMDB4NGh1YnFhdnlmanIiLCJpYXQiOjE3NjcwMDM0MzksImV4cCI6MTc2NzA4OTgzOX0.o106blYjUzh1fhWMgGZtKOuEvtAx29JfUt9DPp3tIxU

{
    "title": "My First Updated Article",
    "content": "This is the content of my first article.",
    "published": false
}

### delete article /DELETE/:ID (protected)
DELETE http://localhost:3000/posts/cmjr0mzva0000gnhuart0qy6q
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtanF5NXVjNDAwMDB4NGh1YnFhdnlmanIiLCJpYXQiOjE3NjcwMDM0MzksImV4cCI6MTc2NzA4OTgzOX0.o106blYjUzh1fhWMgGZtKOuEvtAx29JfUt9DPp3tIxU